### ISSUE TITLE
TODO LIst for basic 1.0 functionality

### ISSUE THREAD

**Issue by iracooke** [marine-omics/movp#1]
- [x] Fix performance details (npus, memory etc) for HPC jobs
- [x] Add Fastp read cleaning step
- [x] Add additional variant callers (eg GATK)
- [x] Add improved diagnostics / QC (eg run multiqc on mapped bam files).
- [x] Allow multiple files per sample (eg across multiple lanes) and treat correctly for GATK
